CREATE TABLE IF NOT EXISTS workflow_runs (
 id BIGSERIAL PRIMARY KEY, run_key VARCHAR(64) NOT NULL UNIQUE, keyword TEXT,
 provider VARCHAR(50), item_code TEXT, status VARCHAR(50) NOT NULL,
 current_step VARCHAR(100), error_message TEXT,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS workflow_logs (
 id BIGSERIAL PRIMARY KEY, run_key VARCHAR(64) NOT NULL, level VARCHAR(20) NOT NULL,
 step VARCHAR(100), message TEXT NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_workflow_logs_run_key ON workflow_logs(run_key);
